//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsRent.Dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolsReservations
    {
        public int ToolReservationID { get; set; }
        public Nullable<int> ReservationID { get; set; }
        public Nullable<int> ToolID { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Reservations Reservations { get; set; }
        public virtual Tools Tools { get; set; }
    }
}
