//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsRent.Dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolReservations
    {
        public int ReservationID { get; set; }
        public string ImePrezime { get; set; }
        public Nullable<System.DateTime> DateTimeTo { get; set; }
        public Nullable<System.DateTime> DateTimeFrom { get; set; }
        public string Note { get; set; }
        public string ToolType { get; set; }
    }
}
